name:  match_lastfm
version: 1.0.0
description: match_lastfm  
author: Masanori Ohgita <mp@ohgita.info>
homepage: https://github.com/mugifly/match_lastfm
dependencies:
  options_file: 0.9.2
  web_components: ">=0.2.5 <0.2.6"
  